# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1D1D20)
$foreground = rgb(E8F6FB)
$color0 = rgb(434347)
$color1 = rgb(3A4450)
$color2 = rgb(50433F)
$color3 = rgb(586975)
$color4 = rgb(736960)
$color5 = rgb(86A2AE)
$color6 = rgb(8EABB7)
$color7 = rgb(D6E9F1)
$color8 = rgb(95A3A9)
$color9 = rgb(4D5B6A)
$color10 = rgb(6A5954)
$color11 = rgb(768C9C)
$color12 = rgb(998C80)
$color13 = rgb(B3D7E7)
$color14 = rgb(BDE4F4)
$color15 = rgb(D6E9F1)
