# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8F6FB
background         #1D1D20
cursor             #A9A7A8

active_tab_foreground     #1D1D20
active_tab_background     #E8F6FB
inactive_tab_foreground   #E8F6FB
inactive_tab_background   #1D1D20

active_border_color   #E8F6FB
inactive_border_color #1D1D20
bell_border_color     #3A4450

color0      #434347
color1		#3A4450
color2		#50433F
color3		#586975
color4		#736960
color5		#86A2AE
color6		#8EABB7
color7		#D6E9F1
color8		#95A3A9
color9		#4D5B6A
color10		#6A5954
color11		#768C9C
color12		#998C80
color13		#B3D7E7
color14		#BDE4F4
color15		#D6E9F1
